// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protocol

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CarsClient is the client API for Cars service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CarsClient interface {
	CreateCar(ctx context.Context, in *Carparams, opts ...grpc.CallOption) (*Errmsg, error)
	GetCar(ctx context.Context, in *Carparams, opts ...grpc.CallOption) (*Carparams, error)
	DeleteCar(ctx context.Context, in *Carparams, opts ...grpc.CallOption) (*Errmsg, error)
	UpdateCar(ctx context.Context, in *Carparams, opts ...grpc.CallOption) (*Errmsg, error)
}

type carsClient struct {
	cc grpc.ClientConnInterface
}

func NewCarsClient(cc grpc.ClientConnInterface) CarsClient {
	return &carsClient{cc}
}

func (c *carsClient) CreateCar(ctx context.Context, in *Carparams, opts ...grpc.CallOption) (*Errmsg, error) {
	out := new(Errmsg)
	err := c.cc.Invoke(ctx, "/grpcpb.Cars/CreateCar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *carsClient) GetCar(ctx context.Context, in *Carparams, opts ...grpc.CallOption) (*Carparams, error) {
	out := new(Carparams)
	err := c.cc.Invoke(ctx, "/grpcpb.Cars/GetCar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *carsClient) DeleteCar(ctx context.Context, in *Carparams, opts ...grpc.CallOption) (*Errmsg, error) {
	out := new(Errmsg)
	err := c.cc.Invoke(ctx, "/grpcpb.Cars/DeleteCar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *carsClient) UpdateCar(ctx context.Context, in *Carparams, opts ...grpc.CallOption) (*Errmsg, error) {
	out := new(Errmsg)
	err := c.cc.Invoke(ctx, "/grpcpb.Cars/UpdateCar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CarsServer is the server API for Cars service.
// All implementations must embed UnimplementedCarsServer
// for forward compatibility
type CarsServer interface {
	CreateCar(context.Context, *Carparams) (*Errmsg, error)
	GetCar(context.Context, *Carparams) (*Carparams, error)
	DeleteCar(context.Context, *Carparams) (*Errmsg, error)
	UpdateCar(context.Context, *Carparams) (*Errmsg, error)
}

// UnimplementedCarsServer must be embedded to have forward compatible implementations.
type UnimplementedCarsServer struct {
}

func (UnimplementedCarsServer) CreateCar(context.Context, *Carparams) (*Errmsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCar not implemented")
}
func (UnimplementedCarsServer) GetCar(context.Context, *Carparams) (*Carparams, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCar not implemented")
}
func (UnimplementedCarsServer) DeleteCar(context.Context, *Carparams) (*Errmsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCar not implemented")
}
func (UnimplementedCarsServer) UpdateCar(context.Context, *Carparams) (*Errmsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCar not implemented")
}

// UnsafeCarsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CarsServer will
// result in compilation errors.
type UnsafeCarsServer interface {
	mustEmbedUnimplementedCarsServer()
}

func RegisterCarsServer(s grpc.ServiceRegistrar, srv CarsServer) {
	s.RegisterService(&Cars_ServiceDesc, srv)
}

func _Cars_CreateCar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Carparams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CarsServer).CreateCar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcpb.Cars/CreateCar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CarsServer).CreateCar(ctx, req.(*Carparams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cars_GetCar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Carparams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CarsServer).GetCar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcpb.Cars/GetCar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CarsServer).GetCar(ctx, req.(*Carparams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cars_DeleteCar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Carparams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CarsServer).DeleteCar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcpb.Cars/DeleteCar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CarsServer).DeleteCar(ctx, req.(*Carparams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cars_UpdateCar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Carparams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CarsServer).UpdateCar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcpb.Cars/UpdateCar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CarsServer).UpdateCar(ctx, req.(*Carparams))
	}
	return interceptor(ctx, in, info, handler)
}

// Cars_ServiceDesc is the grpc.ServiceDesc for Cars service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Cars_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpcpb.Cars",
	HandlerType: (*CarsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCar",
			Handler:    _Cars_CreateCar_Handler,
		},
		{
			MethodName: "GetCar",
			Handler:    _Cars_GetCar_Handler,
		},
		{
			MethodName: "DeleteCar",
			Handler:    _Cars_DeleteCar_Handler,
		},
		{
			MethodName: "UpdateCar",
			Handler:    _Cars_UpdateCar_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protocol/cars.proto",
}
